version: '3'

#https://sebastianbrosch.blog/docker-stack-nginx-mit-php-7-2-und-mysql/
#https://medium.com/swlh/wordpress-deployment-with-nginx-php-fpm-and-mariadb-using-docker-compose-55f59e5c1a
services:
    web:
        depends_on: 
            - php
            - db
        image: nginx:latest
        ports:
            - "8080:80"
        volumes: 
            - ./code:/code
            - ./config/nginx-site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        depends_on:
            - db
        image: custom-php:7.3-fpm
        build:
            context: ./images/custom-php #the location of the docker-file
        volumes:
            - ./code:/code
            - ./config/php-log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
        restart: always
        networks:
            - code-network
    db: # IMPORTANT this is also the hostname for connections -> use "db" instead of "localhost"
        image: mariadb:10.4.8
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: mysql
            MYSQL_DATABASE: appdatabase
            MYSQL_USER: mysql
            MYSQL_PASSWORD: mysql
        networks:
            - code-network

networks:
    code-network:
        driver: bridge